"""create bonds table

Revision ID: 17b51ecffcfd
Revises: 
Create Date: 2026-06-16 23:07:59.996138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b51ecffcfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('bond_type', sa.String(length=50), nullable=True),
    sa.Column('nominal', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bonds')
    # ### end Alembic commands ###
